# Generated by Django 5.0 on 2026-06-06 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('piso', models.CharField(max_length=50)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('sillas', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('pizarra', models.CharField(max_length=50)),
                ('television', models.CharField(max_length=50)),
                ('vista', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['piso'], name='salas_sala_piso_5829b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.CharField(max_length=20)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='salas.sala')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['dia', 'bloque'],
                'unique_together': {('sala', 'bloque', 'dia')},
            },
        ),
    ]
