# Generated by Django 6.0.6 on 2026-06-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('piso', models.CharField(choices=[('Piso 1', 'Piso 1'), ('Piso -1', 'Piso -1'), ('Piso 2', 'Piso 2')], max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
                ('sillas', models.PositiveIntegerField()),
                ('pizarra', models.CharField(max_length=30)),
                ('multimedia', models.BooleanField(default=False)),
                ('entorno', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
