# Generated by Django 6.0.6 on 2026-06-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='disponibilidad',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sala',
            name='piso',
            field=models.CharField(max_length=50),
        ),
    ]
