# Generated by Django 6.0.6 on 2026-06-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
